development:
  adapter: postgresql
  encoding: unicode
  database: dorloti_development
  pool: 5
  username: mashype
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dorloti_test
  pool: 5
  username: mashype
  password:
