# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08173a7b0c2596225a12b5eda7117e752356d5c233056c87a002a704664e1aa145b9247738024ae83ab0a90fadcb5cdcf902fd4af0c33501a16140d7513fb6b6
  stripe_publishable_key: pk_test_vG3uKuRBa3SChlHNZBIXzGam
  stripe_secret_key: sk_test_fkJAQRUFD5sxErgWi54XO8BR

test:
  secret_key_base: c99316a0ec443f5b22f31536ac063f802e7d6792ab66cd692d2ab69e6ce889b1b2beca98dd71f33b8b17bfb51612f28d2787ba5d66a4e8a659cdcc7c5ad7388f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>

